# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 2.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: NuGet Restore
      run: nuget restore BidTrainer.sln      
    - name: Build
      run: dotnet build --no-restore
      # Restore from cache the previously built ports. If cache-miss, download, build vcpkg.
    - name: Restore from cache and install vcpkg
      # Download and build vcpkg, without installing any port. If content is cached already, it is a no-op.
      uses: lukka/run-vcpkg@v11
      # Now that vcpkg is installed, it is being used to run with desired arguments.
    - name: Install SQLiteCpp and nlohmann-json using vcpg      
      run: |
        $VCPKG_ROOT/vcpkg install SQLiteCpp:x64-windows
        $VCPKG_ROOT/vcpkg install nlohmann-json:x64-windows
        $VCPKG_ROOT/vcpkg integrate install
      shell: bash      
    - name: Test
      run: dotnet test --no-build --verbosity normal
