# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
      with:
          submodules: true      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 2.1.x
    - name: Set default Xamarin SDK versions
      run: |
        $VM_ASSETS/select-xamarin-sdk-v2.sh --mono=6.12 --android=14
    - name: add source to nuget 
      run: dotnet nuget add source "https://nuget.pkg.github.com/YkeSmit1/index.json" --name "githubfeed" --username "YkeSmit1" --password "${{ secrets.GITHUB_TOKEN }}"
    - name: Restore dependencies
      run: dotnet restore
    - name: NuGet Restore
      run: nuget restore App.BidTrainer.sln      
      # Restore from cache the previously built ports. If cache-miss, download, build vcpkg.
    - name: Restore from cache and install vcpkg
      # Download and build vcpkg, without installing any port. If content is cached already, it is a no-op.
      uses: lukka/run-vcpkg@v11
      # Now that vcpkg is installed, it is being used to run with desired arguments.
    - name: Install SQLiteCpp and nlohmann-json using vcpg      
      run: |
        $VCPKG_ROOT/vcpkg install SQLiteCpp:x64-windows
        $VCPKG_ROOT/vcpkg install nlohmann-json:x64-windows
        $VCPKG_ROOT/vcpkg integrate install
      shell: bash      
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
