# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
          submodules: true      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '2.0.x'
        source-url: https://nuget.pkg.github.com/YkeSmit1/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}        
    - name: Restore dependencies
      run: dotnet restore
    - name: NuGet Restore
      run: nuget restore App.BidTrainer.sln
      # Restore from cache the previously built ports. If cache-miss, download, build vcpkg.
    - name: Restore from cache and install vcpkg
      # Download and build vcpkg, without installing any port. If content is cached already, it is a no-op.
      uses: lukka/run-vcpkg@v11
      # Now that vcpkg is installed, it is being used to run with desired arguments.
    - name: Install SQLiteCpp and nlohmann-json using vcpg      
      run: |
        $VCPKG_ROOT/vcpkg install SQLiteCpp:x64-windows
        $VCPKG_ROOT/vcpkg install nlohmann-json:x64-windows
        $VCPKG_ROOT/vcpkg integrate install
      shell: bash      
    - name: Build
      run: msbuild App.BidTrainer.sln /t:PackageForAndroid /p:Configuration=Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
